server:
  port: ${SERVER_PORT:8090}

spring:
  datasource:
    driver-class-name: net.ucanaccess.jdbc.UcanaccessDriver
    url: jdbc:ucanaccess://C:/Users/Leo/AGC00E19.MDB
    username: Leo_desarrollo
    password: 111111
  jpa:
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: net.ucanaccess.hibernate.dialect.UcanaccessDialect
        temp.use_jdbc_metadata_defaults: false
        hbm2ddl.auto: none # Solo necesitas una de estas dos
      globally_quoted_identifiers: true

management:
  endpoints:
    web:
      exposure:
        include: "*"